CommitField/commitfield

build.gradle.kts
src/main/java/cmf/commitField/global/springDoc/SwaggerConfig.java

- 의존성 추가, 스웨거 도입 
어떤 변경 사항이 있나요?

Feat: 의존성 추가, 스웨거 도입

---

src/main/java/cmf/commitField/domain/main/main/controller/ApiV1MainController.java
src/main/java/cmf/commitField/global/config/AppConfig.java
src/main/resources/application-prod.yml
src/main/resources/application.yml

#6 
배포 중 jpa 설정 오류로 application.yml 수정
어떤 변경 사항이 있나요?

chore : application.yml file fix

---

.github/workflows/deploy.yml

#6 
서버 재배포로 인스턴스 id 변경
어떤 변경 사항이 있나요?

chore : instance-ids fix (#6)

---

src/main/java/cmf/commitField/global/config/CustomWebMvcConfig.java

#6 
web config file 추가
어떤 변경 사항이 있나요?

chore : webconfig file add (#6)

---

src/main/resources/application-prod.yml
src/main/resources/application-secret.yml.default

secret yml redis pw 추가
#6 
어떤 변경 사항이 있나요?

chore : secret yml fix (#6)

---

src/main/resources/application-secret.yml.default

#6 
application-secret.yml redis pw 수정
어떤 변경 사항이 있나요?

chore : pw fix

---

src/main/java/cmf/commitField/domain/main/main/controller/ApiV1MainController.java
src/main/java/cmf/commitField/domain/user/entity/CustomOAuth2User.java
src/main/java/cmf/commitField/domain/user/entity/User.java
src/main/java/cmf/commitField/domain/user/repository/UserRepository.java
src/main/java/cmf/commitField/domain/user/service/CustomOAuth2UserService.java
src/main/java/cmf/commitField/global/security/SecurityConfig.java

#5
CustomOauthUser 작성, Security 설정 추가, DB 저장 추가
어떤 변경 사항이 있나요?
- [ v ] 새로운 기능 추가
- [ v ] 커밋 메시지 컨벤션에 맞게 작성했습니다.

feat: 로그인/회원가입 기능 구현 #5

---

src/main/resources/application.yml

#38 
Swagger 페이지 접속 URL 및 정렬 변경
어떤 변경 사항이 있나요?
application.yml 부분에 swagger 설정 부분
swagger 설정 중에 어떤 url을 필터링 어떻게 할까요? 현재 /api 패스만 보이도록 설정한거 주석처리되어 있습니다.

#38 Feat: Swagger설정변경

---

src/main/resources/application-secret.yml.default

#6 
배포 중 git token 오류 수정
어떤 변경 사항이 있나요?

fix : gittoken 추가 (#6)

---

build.gradle.kts
src/main/resources/application-prod.yml

#6 
redis actuator 추가
어떤 변경 사항이 있나요?

chore : redis actuator 추가 (#6)

---

src/main/java/cmf/commitField/global/security/SecurityConfig.java
src/main/resources/application.yml

#6 
local redis 비활성화, 시큐리티 주석처리
어떤 변경 사항이 있나요?

fix : local redis 비활성화, 시큐리티 주석처리

---

src/main/resources/application-dev.yml
src/main/resources/application.yml

#6 
redis 설정 코드 이동
어떤 변경 사항이 있나요?

rename : redis 설정 코드 이동 (#6)

---

.gitignore
build.gradle.kts
ec2/main.tf
ec2/variables.tf
s3/main.tf
s3/variables.tf
src/main/java/cmf/commitField/domain/admin/controller/ApiV1PetImgController.java
src/main/java/cmf/commitField/global/aws/s3/S3Cleaner.java
src/main/java/cmf/commitField/global/aws/s3/S3Config.java
src/main/java/cmf/commitField/global/aws/s3/S3Service.java

#6 
s3 버킷 생성 및 이미지 생성 및 삭제
어떤 변경 사항이 있나요?

chore : s3 버킷 생성 및 이미지 생성 및 삭제

---

src/main/java/cmf/commitField/domain/admin/controller/ApiV1PetImgController.java

s3 test uri fix
어떤 변경 사항이 있나요?

rename : s3 test uri fix

---

src/main/java/cmf/commitField/domain/noti/noti/controller/ApiV1NotiController.java
src/main/java/cmf/commitField/domain/noti/noti/dto/NotiDto.java
src/main/java/cmf/commitField/domain/noti/noti/entity/Noti.java
src/main/java/cmf/commitField/domain/noti/noti/entity/NotiMessageTemplates.java
src/main/java/cmf/commitField/domain/noti/noti/repository/NotiRepository.java
src/main/java/cmf/commitField/domain/noti/noti/service/NotiService.java
src/main/java/cmf/commitField/domain/user/entity/User.java
src/main/java/cmf/commitField/domain/user/service/CustomOAuth2UserService.java
src/main/java/cmf/commitField/global/error/ErrorCode.java
src/main/java/cmf/commitField/global/scheduler/SeasonScheduler.java
src/main/java/cmf/commitField/global/websocket/ChatWebSocketHandler.java
src/main/java/cmf/commitField/global/websocket/NotiWebSocketHandler.java
src/main/resources/application.yml

#81 
알림 데이터 저장 및 프론트 연동 테스트
어떤 변경 사항이 있나요?

feat : 알림 데이터 저장 및 프론트 연동 테스트 (#18)

---

src/main/java/cmf/commitField/domain/commit/scheduler/CommitScheduler.java
src/main/java/cmf/commitField/domain/commit/scheduler/CommitUpdateEvent.java
src/main/java/cmf/commitField/domain/commit/scheduler/CommitUpdateListener.java
src/main/java/cmf/commitField/domain/commit/scheduler/CommitUpdateService.java
src/main/java/cmf/commitField/domain/pet/controller/PetController.java
src/main/java/cmf/commitField/domain/pet/controller/UserPetController.java
src/main/java/cmf/commitField/domain/pet/dto/UserPetDto.java

fix: pr 오류 수정

---

src/main/java/cmf/commitField/domain/commit/scheduler/CommitScheduler.java
src/main/java/cmf/commitField/domain/commit/scheduler/CommitUpdateEvent.java
src/main/java/cmf/commitField/domain/commit/scheduler/CommitUpdateListener.java
src/main/java/cmf/commitField/domain/commit/scheduler/CommitUpdateService.java
src/main/java/cmf/commitField/domain/commit/totalCommit/service/TotalCommitService.java
src/main/java/cmf/commitField/domain/pet/entity/Pet.java
src/main/java/cmf/commitField/domain/pet/entity/PetGrow.java
src/main/java/cmf/commitField/domain/pet/service/PetService.java
src/main/java/cmf/commitField/domain/user/controller/LogoutController.java
src/main/java/cmf/commitField/domain/user/dto/UserInfoDto.java
src/main/java/cmf/commitField/domain/user/entity/User.java
src/main/java/cmf/commitField/domain/user/service/CustomOAuth2UserService.java
src/main/java/cmf/commitField/domain/user/service/UserService.java
src/main/java/cmf/commitField/global/security/SecurityConfig.java

#97
새 커밋 발생시에만 user와 pet 경험치 자동으로 업데이트되게끔 수정 완료
어떤 변경 사항이 있나요?

feat: 스프링 이벤트를 이용해 경험치, 펫에 연동 완료

---

src/main/java/cmf/commitField/global/config/RedisConfig.java
src/main/resources/application-prod.yml
src/main/resources/application.yml

fix: 레디스 권한 문제 수정

---

.github/workflows/deploy.yml
src/main/resources/application.yml

fix:오류 해결 시도

---

src/main/java/cmf/commitField/global/config/RedisConfig.java

dev > main merge

---

.github/workflows/deploy.yml

instance id fix
어떤 변경 사항이 있나요?

chore : instance id fix

---

src/main/java/cmf/commitField/domain/commit/scheduler/CommitUpdateService.java
src/main/java/cmf/commitField/domain/pet/entity/PetGrow.java
src/main/java/cmf/commitField/domain/user/controller/UserController.java
src/main/java/cmf/commitField/domain/user/dto/UserRegacyDto.java
src/main/java/cmf/commitField/domain/user/entity/Tier.java
src/main/java/cmf/commitField/domain/user/entity/TierRegacy.java
src/main/java/cmf/commitField/domain/user/entity/User.java
src/main/java/cmf/commitField/domain/user/repository/TierRegacyRepository.java
src/main/java/cmf/commitField/domain/user/service/CustomOAuth2UserService.java
src/main/java/cmf/commitField/domain/user/service/UserService.java
src/main/resources/application-dev.yml
src/main/resources/application.yml

#132 
획득 업적 관련 로직 추가
어떤 변경 사항이 있나요?

feat: 획득 티어 관련 로직 추가
